apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: demo-kube-cluster
spec:
  hosts:
    - ssh:
        address: 10.0.0.2
        user: demo
        port: 2222
        keyPath: ~/.ssh/id_ed25519
      role: controller+worker
      privateInterface: ens10
      installFlags:
        - --kubelet-extra-args "--node-ip=10.0.0.2"
    - ssh:
        address: 10.0.0.3
        user: demo
        port: 2222
        keyPath: ~/.ssh/id_ed25519
      role: worker
      privateInterface: ens10
      installFlags:
        - --kubelet-extra-args "--node-ip=10.0.0.3"
    - ssh:
        address: 10.0.0.4
        user: demo
        port: 2222
        keyPath: ~/.ssh/id_ed25519
      role: worker
      privateInterface: ens10
      installFlags:
        - --kubelet-extra-args "--node-ip=10.0.0.4"
    - ssh:
        address: 10.0.0.5
        user: demo
        port: 2222
        keyPath: ~/.ssh/id_ed25519
      role: worker
      privateInterface: ens10
      installFlags:
        - --kubelet-extra-args "--node-ip=10.0.0.5"
  k0s:
    version: 1.24.2+k0s.0
    config:
      spec:
        api:
          externalAddress: kubedemo.example.org
          sans:
            - kubedemo.example.org
        storage:
          etcd:
            peerAddress: 10.0.0.2
        network:
          provider: calico
